### ISSUE TITLE
App boot TODO

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#1462]
- [x] Upgrade Webpack: https://github.com/webpack/webpack.js.org/blob/dc072b6512610893290b25882fb46efe0493bbb5/src/content/guides/migrating.md
- [x] Request a boot timeout increase with Heroku
- [ ] See if we can upgrade any of the Babel related compilation stuff to see if there are speed increases
- [ ] Upgrade Node
- [ ]  Any low-hanging fruit in Webpack configuration
- [ ] Pre-compile app?
- [ ] https://glebbahmutov.com/blog/faster-node-app-require/
