### ISSUE TITLE
Channel TODO

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#2009]
## Remaining

- [x] SSR the first 'page' of connectables
- [x] Channel connectables filter
- [x] Shareable channel view
- [x] ["You've reached your limit"](http://static.damonzucconi.com/_capture/ITGttxlz3r.png) add block CTA
- [x] Rewire Pusher updates
- [x] Followers page
- [x] Metatags (title, etc)
- [x] Hide AddBlock CTA on private share channels by using the new can field
- [x] [Empty channel message](http://static.damonzucconi.com/_capture/yMjTXcd42c.png)
- [x] Embed view (/embed)
- [ ] Confirm connection destruction in context menu
